name: Discord reminder to menu

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * 5" # é‡‘æ›œæ—¥ã®21:00ã«å®Ÿè¡Œ

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Remind on Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_MENU_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_MENU_WEBHOOK_TOKEN }}
          color: "16711680"
          username: "ãƒªãƒã‚¤ãƒ³ãƒ€ãƒ¼"
          message: "ğŸšé€±æœ«ã®è²·ã„ç‰©ã«å‘ã‘ã¦æ¥é€±ã®ãƒ¡ãƒ‹ãƒ¥ãƒ¼ã‚’è€ƒãˆã¾ã—ã‚‡ã†ï¼Â¥nğŸ²é£Ÿã¹ãŸã„ã‚‚ã®ãŒãªã‘ã‚Œã°åœ¨åº«ã‚’ãƒ«ãƒ¼ãƒ¬ãƒƒãƒˆ"
